// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var assert, bscoords, i, t, vectors;
  assert = require('assert');
  bscoords = require('./lib/bscoords');
  vectors = [
  ];

  bscoords.init({
    //openCellIDApiKey: 'insert your own',
    timeout: 5000
  });

  i = 0;

  t = setInterval(function() {
    var ii;
    ii = i++;
    bscoords.request(vectors[ii].req.mcc, vectors[ii].req.mnc, vectors[ii].req.lac, vectors[ii].req.cid, vectors[ii].req.net, function(err, coords) {
      var prov, ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9, ref10, ref11, results, testResult;
      console.log(vectors[ii].req.cid + "," + vectors[ii].req.lac + "," + vectors[ii].req.mcc + "," + vectors[ii].req.mnc + "," + ((ref = coords.google) != null ? ref.lat : void 0) + "," + ((ref1 = coords.google) != null ? ref1.lon : void 0) + "," + ((ref2 = coords.yandex_bs) != null ? ref2.lat : void 0) + "," + ((ref3 = coords.yandex_bs) != null ? ref3.lon : void 0) + "," + ((ref4 = coords.yandex_cell) != null ? ref4.lat : void 0) + "," + ((ref5 = coords.yandex_cell) != null ? ref5.lon : void 0) + "," + ((ref6 = coords.opencellid) != null ? ref6.lat : void 0) + "," + ((ref7 = coords.opencellid) != null ? ref7.lon : void 0) + "," + ((ref8 = coords.mozLocation) != null ? ref8.lat : void 0) + "," + ((ref9 = coords.mozLocation) != null ? ref9.lon : void 0) + "," + ((ref10 = coords.mylinkov) != null ? ref10.lat : void 0) + "," + ((ref11 = coords.mylinkov) != null ? ref11.lon : void 0));
      results = [];
      return results;
    });
    if (i >= vectors.length) {
      return clearInterval(t);
    }
  }, 3000);

}).call(this);
