figure(1);
title('Speed Estimation Accuracy')

legend_string = {'Raw speed estimation' ...
    'Filtered speed estimation'};

label_string = {'10%' ...
    '20%' ...
    '30%' ...
    '40%' ...
    '50%' ...       
    '60%' ...
    '70%' ...
    '80%' ...
    '90%' ...
    '>= 100%'};

raw_speed_estimation_error = [335, 164, 191, 111, 117, 149, 233, 130, 33, 492]
% filtered_speed_estimation_error = [140, 137, 79, 65, 0, 58, 67, 0, 0, 25]
filtered_speed_estimation_error = [140, 137, 79, 65, 3, 58, 67, 3, 3, 25]
speed_estimation_error = [raw_speed_estimation_error', filtered_speed_estimation_error']

bar(speed_estimation_error);
set(gca,'FontSize',20);
set(gca, 'XTickLabel', label_string);
ylabel_hand=ylabel('Number of records');
set(ylabel_hand,'Fontname', 'Times New Roman', 'Fontsize', 20);
xlabel_hand=xlabel('Speed estimation errors');
set(xlabel_hand,'Fontname', 'Times New Roman', 'Fontsize', 20);
legend_hand = legend(legend_string);
set(legend_hand,'Fontname', 'Times New Roman', 'Fontsize', 20);

